export interface Student {
  id: number,
  fullName: string,
  age: any,
  mail: string,
  class: string,
}

export const Data: Student[] = [
  { id: 1, fullName: "Mazin", age: 15, mail: "mazinmahgoub91@gmail.com", class: "3/B p" },
  { id: 2, fullName: "Omar", age: 15, mail: "omar123@gmail.com", class: "3/B p" },
  { id: 3, fullName: "Mohamed", age: 15, mail: "mohamed456@gmail.com", class: "3/B p" },
  { id: 4, fullName: "Sara", age: 14, mail: "sara789@gmail.com", class: "3/B p" },
  { id: 5, fullName: "Ali", age: 15, mail: "ali.ahmed@gmail.com", class: "3/B p" },
  { id: 6, fullName: "Fatma", age: 14, mail: "fatma.mostafa@gmail.com", class: "3/B p" },
  { id: 7, fullName: "Youssef", age: 15, mail: "youssef.nabil@gmail.com", class: "3/B p" },
  { id: 8, fullName: "Aya", age: 14, mail: "aya.khaled@gmail.com", class: "3/B p" },
  { id: 9, fullName: "Kareem", age: 15, mail: "kareem.samir@gmail.com", class: "3/B p" },
  { id: 10, fullName: "Nour", age: 14, mail: "nour.laila@gmail.com", class: "3/B p" },
  { id: 11, fullName: "Hana", age: 14, mail: "hana.ali@gmail.com", class: "3/B p" },
  { id: 12, fullName: "Tarek", age: 15, mail: "tarek.fouad@gmail.com", class: "3/B p" },
  { id: 13, fullName: "Laila", age: 14, mail: "laila.ahmed@gmail.com", class: "3/B p" },
  { id: 14, fullName: "Adham", age: 15, mail: "adham.nour@gmail.com", class: "3/B p" },
  { id: 15, fullName: "Marwan", age: 15, mail: "marwan.ramy@gmail.com", class: "3/B p" },
  { id: 16, fullName: "Nada", age: 14, mail: "nada.sameh@gmail.com", class: "3/B p" },
  { id: 17, fullName: "Ziad", age: 15, mail: "ziad.hassan@gmail.com", class: "3/B p" },
  { id: 18, fullName: "Salma", age: 14, mail: "salma.omar@gmail.com", class: "3/B p" },
  { id: 19, fullName: "Hazem", age: 15, mail: "hazem.mohsen@gmail.com", class: "3/B p" },
  { id: 20, fullName: "Jana", age: 14, mail: "jana.ghassan@gmail.com", class: "3/B p" },
  { id: 21, fullName: "Bassel", age: 15, mail: "bassel.mourad@gmail.com", class: "3/B p" },
  { id: 22, fullName: "Reem", age: 14, mail: "reem.kamal@gmail.com", class: "3/B p" },
  { id: 23, fullName: "Hussein", age: 15, mail: "hussein.mahdy@gmail.com", class: "3/B p" },
  { id: 24, fullName: "Menna", age: 14, mail: "menna.samir@gmail.com", class: "3/B p" },
  { id: 25, fullName: "Eslam", age: 15, mail: "eslam.farouk@gmail.com", class: "3/B p" },
];
